"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

NAME = '文件加密系统'
APP = ['src/main.py']
DATA_FILES = ['src/']
OPTIONS = {
    "iconfile": "sysicon.icns"
}

setup(
    name=NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    requires=['kivy'],
    setup_requires=['py2app'],
)
