RelativeLayout:
    Label:
        text_size: self.size
        canvas.before:
            Color:
                rgba: 1, 0.5, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        halign: "left"
        valign: "center"
        font_size: 60
        text: 'log1.txtfejiofjweiofjejeiofjofjefeoj'
        padding_x: 30
        size_hint: 1, 1
    Label:
        text_size: self.size
        halign: "right"
        valign: "center"
        font_size: 30
        text: '2022.11.1'
        padding_x: 30
        size_hint: 1, 1